### PR TITLE
Bumped to v0.11.7 for ARMv7

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by alexellis** [comment]
Hi John, can you say how you tested the change etc? Thanks

**Review by alexellis — APPROVED** [review]
Approved subject to testing on the device with Docker.

**Comment by ghost** [comment]
@alexellis I built the image on my Raspberry Pi 3 Model B to update my Ghost blog to 0.11.7. I initially tried 0.11.5 last week but had no luck building it on the RPi.

**Comment by alexellis** [comment]
Did it also boot up fine?

**Comment by ghost** [comment]
@alexellis Yes, my blog is currently running on the image I built using the exact Dockerfile.

**Pull request merged**
